@startuml
!pragma useIntermediatePackages false

annotation "AutoFactory" as com.google.auto.factory.AutoFactory {
  + {abstract}String className()
  + {abstract}Class<?>[] implementing()
  + {abstract}Class<?> extending()
  + {abstract}boolean allowSubclasses()
}
annotation "Inject" as jakarta.inject.Inject {
}
class "RedisCacheAutoConfiguration" as org.toolkit.cache.redis.autoconfigure.RedisCacheAutoConfiguration {
}
class "RedisCache" as org.toolkit.cache.redis.cache.RedisCache<K, V> {
}
class "RedisCacheFactory" as org.toolkit.cache.redis.cache.RedisCacheFactory {
  +RedisCache<K, V> create()
}
@enduml
