@startuml
!pragma useIntermediatePackages false

annotation "GwtCompatible" as com.google.common.annotations.GwtCompatible {
  + {abstract}boolean serializable()
  + {abstract}boolean emulated()
}
annotation "ElementTypesAreNonnullByDefault" as com.google.common.collect.ElementTypesAreNonnullByDefault {
}
annotation "ParametricNullness" as com.google.common.collect.ParametricNullness {
}
interface "Table" as com.google.common.collect.Table<R extends @Nullable Object, C extends @Nullable Object, V extends @Nullable Object> {
  + {abstract}boolean contains(Object, Object)
  + {abstract}boolean containsRow(Object)
  + {abstract}boolean containsColumn(Object)
  + {abstract}boolean containsValue(Object)
  + {abstract}V get(Object, Object)
  + {abstract}boolean isEmpty()
  + {abstract}int size()
  + {abstract}void clear()
  + {abstract}V put(R, C, V)
  + {abstract}void putAll(Table<? extends R, ? extends C, ? extends V>)
  + {abstract}V remove(Object, Object)
  + {abstract}Map<C, V> row(R)
  + {abstract}Map<R, V> column(C)
  + {abstract}Set<Cell<R, C, V>> cellSet()
  + {abstract}Set<R> rowKeySet()
  + {abstract}Set<C> columnKeySet()
  + {abstract}Collection<V> values()
  + {abstract}Map<R, Map<C, V>> rowMap()
  + {abstract}Map<C, Map<R, V>> columnMap()
}
interface "Table$Cell" as com.google.common.collect.Table$Cell<R extends @Nullable Object, C extends @Nullable Object, V extends @Nullable Object> {
  + {abstract}R getRowKey()
  + {abstract}C getColumnKey()
  + {abstract}V getValue()
}
annotation "CanIgnoreReturnValue" as com.google.errorprone.annotations.CanIgnoreReturnValue {
}
annotation "CompatibleWith" as com.google.errorprone.annotations.CompatibleWith {
  + {abstract}String value()
}
annotation "DoNotMock" as com.google.errorprone.annotations.DoNotMock {
  + {abstract}String value()
}
annotation "CheckForNull" as javax.annotation.CheckForNull {
}
annotation "Nonnull" as javax.annotation.Nonnull {
  + {abstract}When when()
}
annotation "TypeQualifier" as javax.annotation.meta.TypeQualifier {
  + {abstract}Class<?> applicableTo()
}
annotation "TypeQualifierDefault" as javax.annotation.meta.TypeQualifierDefault {
  + {abstract}ElementType[] value()
}
annotation "TypeQualifierNickname" as javax.annotation.meta.TypeQualifierNickname {
}
enum "When" as javax.annotation.meta.When {
  ALWAYS
  UNKNOWN
  MAYBE
  NEVER
}
interface "Function" as kotlin.Function<R> {
}
annotation "Metadata" as kotlin.Metadata {
  __
  + {abstract}int k()
  + {abstract}int[] mv()
  + {abstract}int[] bv()
  + {abstract}String[] d1()
  + {abstract}String[] d2()
  + {abstract}String xs()
  + {abstract}String pn()
  + {abstract}int xi()
}
annotation "SinceKotlin" as kotlin.SinceKotlin {
  + {abstract}String version()
}
enum "AnnotationRetention" as kotlin.annotation.AnnotationRetention {
  SOURCE
  BINARY
  RUNTIME
  __
  + {static}EnumEntries<AnnotationRetention> getEntries()
}
enum "AnnotationTarget" as kotlin.annotation.AnnotationTarget {
  CLASS
  ANNOTATION_CLASS
  TYPE_PARAMETER
  PROPERTY
  FIELD
  LOCAL_VARIABLE
  VALUE_PARAMETER
  CONSTRUCTOR
  FUNCTION
  PROPERTY_GETTER
  PROPERTY_SETTER
  TYPE
  EXPRESSION
  FILE
  TYPEALIAS
  __
  + {static}EnumEntries<AnnotationTarget> getEntries()
}
annotation "MustBeDocumented" as kotlin.annotation.MustBeDocumented {
}
annotation "Retention" as kotlin.annotation.Retention {
  + {abstract}AnnotationRetention value()
}
annotation "Target" as kotlin.annotation.Target {
  + {abstract}AnnotationTarget[] allowedTargets()
}
annotation "JvmName" as kotlin.jvm.JvmName {
  + {abstract}String name()
}
annotation "JvmOverloads" as kotlin.jvm.JvmOverloads {
}
interface "Function0" as kotlin.jvm.functions.Function0<R> {
  + {abstract}R invoke()
}
interface "Function1" as kotlin.jvm.functions.Function1<P1, R> {
  + {abstract}R invoke(P1)
}
interface "Function2" as kotlin.jvm.functions.Function2<P1, P2, R> {
  + {abstract}R invoke(P1, P2)
}
interface "FunctionBase" as kotlin.jvm.internal.FunctionBase<R> {
  + {abstract}int getArity()
}
abstract class "Lambda" as kotlin.jvm.internal.Lambda<R> {
  +int getArity()
}
annotation "SourceDebugExtension" as kotlin.jvm.internal.SourceDebugExtension {
  + {abstract}String[] value()
}
interface "KMappedMarker" as kotlin.jvm.internal.markers.KMappedMarker {
}
interface "KMutableCollection" as kotlin.jvm.internal.markers.KMutableCollection {
}
interface "KMutableIterable" as kotlin.jvm.internal.markers.KMutableIterable {
}
interface "KMutableIterator" as kotlin.jvm.internal.markers.KMutableIterator {
}
interface "KMutableList" as kotlin.jvm.internal.markers.KMutableList {
}
annotation "NonNls" as org.jetbrains.annotations.NonNls {
}
annotation "NotNull" as org.jetbrains.annotations.NotNull {
  + {abstract}String value()
  + {abstract}Class<? extends Exception> exception()
}
annotation "Nullable" as org.jetbrains.annotations.Nullable {
  + {abstract}String value()
}
class "Edge" as org.toolkit4j.collection.graph.Edge<T> {
  +T getSource()
  +T getTarget()
  +Double getWeight()
  +T component1()
  +T component2()
  +Double component3()
  +Edge<T> copy(T, T, Double)
}
interface "Graph" as org.toolkit4j.collection.graph.Graph<T> {
  + {abstract}void addVertex(T)
  + {abstract}void addEdge(T, T, Double)
  + {abstract}List<Edge<T>> getNeighbors(T)
  + {abstract}void dfs(T, Set<T>)
  + {abstract}void bfs(T)
  + {abstract}void removeVertex(T)
  + {abstract}void removeEdge(T, T)
  + {abstract}boolean containsVertex(T)
  + {abstract}Set<T> getAllVertices()
  + {abstract}List<Edge<T>> getAllEdges()
}
class "UndirectedGraph" as org.toolkit4j.collection.graph.UndirectedGraph<T> {
  +void addVertex(T)
  +void addEdge(T, T, Double)
  +List<Edge<T>> getNeighbors(T)
  +void dfs(T, Set<T>)
  +void bfs(T)
  +void removeVertex(T)
  +void removeEdge(T, T)
  +boolean containsVertex(T)
  +Set<T> getAllVertices()
  +List<Edge<T>> getAllEdges()
}
class "UndirectedGraph$1" as org.toolkit4j.collection.graph.UndirectedGraph$addVertex$1 {
  ..
  + {static}1 INSTANCE
  __
  +List<Edge<T>> invoke(T)
}
class "UndirectedGraph$1" as org.toolkit4j.collection.graph.UndirectedGraph$removeEdge$1 {
  +Boolean invoke(Edge<T>)
}
class "UndirectedGraph$2" as org.toolkit4j.collection.graph.UndirectedGraph$removeEdge$2 {
  +Boolean invoke(Edge<T>)
}
class "UndirectedGraph$1" as org.toolkit4j.collection.graph.UndirectedGraph$removeVertex$1$1 {
  +Boolean invoke(Edge<T>)
}
class "HashQueueMap" as org.toolkit4j.collection.other.HashQueueMap<K, T> {
  +boolean containsKey(Object)
  +boolean containsValue(Queue<T>)
  +Queue<T> get(K)
  +boolean isEmpty()
  +Set<Entry<K, Queue<T>>> getEntries()
  +Set<K> getKeys()
  +int getSize()
  +Collection<Queue<T>> getValues()
  +T element(K, T)
  +T poll(K)
  +void offer(K, T)
  +void add(K, T)
  +void peek(K)
  +HashQueueMap<K, T> copy(HashMap<K, Queue<T>>)
  +void clear()
  +Queue<T> put(K, Queue<T>)
  +void putAll(Map<? extends K, ? extends Queue<T>>)
  +Queue<T> remove(Object)
  +boolean remove(Object, Object)
  +void replaceAll(BiFunction<? super K, ? super Queue<T>, ? extends Queue<T>>)
  +Queue<T> putIfAbsent(K, Queue<T>)
  +boolean replace(K, Queue<T>, Queue<T>)
  +Queue<T> replace(K, Queue<T>)
  +Queue<T> computeIfAbsent(K, Function<? super K, ? extends Queue<T>>)
  +Queue<T> computeIfPresent(K, BiFunction<? super K, ? super Queue<T>, ? extends Queue<T>>)
  +Queue<T> compute(K, BiFunction<? super K, ? super Queue<T>, ? extends Queue<T>>)
  +Queue<T> merge(K, Queue<T>, BiFunction<? super Queue<T>, ? super Queue<T>, ? extends Queue<T>>)
  +boolean containsValue(Object)
  +Set<Entry<K, Queue<T>>> entrySet()
  +Set<K> keySet()
  +int size()
  +Collection<Queue<T>> values()
}
class "HashQueueMap$1" as org.toolkit4j.collection.other.HashQueueMap$add$1$1 {
  + {static}1 INSTANCE
  __
  +Queue<T> invoke(K)
}
class "HashQueueMap$1" as org.toolkit4j.collection.other.HashQueueMap$offer$1$1 {
  + {static}1 INSTANCE
  __
  +Queue<T> invoke(K)
}
interface "PageableCollection" as org.toolkit4j.collection.pageable.PageableCollection<T, C extends Collection<? extends T>> {
  + {abstract}int getPageNo()
  + {abstract}void setPageNo(int)
  + {abstract}int getPageSize()
  + {abstract}void setPageSize(int)
  + {abstract}C page(int, int)
  +void checkPageArgument(int, int)
  + {abstract}int totalPage(int)
  + {abstract}int current()
  + {abstract}int totalSize()
  + {abstract}boolean hasNextPage()
  + {abstract}boolean hasPreviousPage()
  + {abstract}int getNextPage()
  + {abstract}int getPreviousPage()
}
class "PageableList" as org.toolkit4j.collection.pageable.PageableList<T> {
  +boolean add(T)
  +void add(int, T)
  +boolean addAll(int, Collection<? extends T>)
  +boolean addAll(Collection<? extends T>)
  +void clear()
  +ListIterator<T> listIterator()
  +ListIterator<T> listIterator(int)
  +boolean remove(Object)
  +boolean removeAll(Collection<? extends Object>)
  +T removeAt(int)
  +boolean retainAll(Collection<? extends Object>)
  +T set(int, T)
  +List<T> subList(int, int)
  +boolean isEmpty()
  +boolean contains(Object)
  +Iterator<T> iterator()
  +boolean containsAll(Collection<? extends Object>)
  +T get(int)
  +int indexOf(Object)
  +int lastIndexOf(Object)
  +int getSize()
  +int getPageNo()
  +void setPageNo(int)
  +int getPageSize()
  +void setPageSize(int)
  +List<T> page(int, int)
  +int totalPage(int)
  +int current()
  +int totalSize()
  +boolean hasNextPage()
  +boolean hasPreviousPage()
  +int getNextPage()
  +int getPreviousPage()
  +int component2()
  +int component3()
  +PageableList<T> copy(List<T>, int, int)
  +T remove(int)
  +int size()
  +T[] toArray(T[])
  +Object[] toArray()
}
class "PageableSet" as org.toolkit4j.collection.pageable.PageableSet<T> {
  +Comparator<? super T> comparator()
  +SortedSet<T> subSet(T, T)
  +SortedSet<T> headSet(T)
  +SortedSet<T> tailSet(T)
  +T first()
  +T last()
  +boolean add(T)
  +boolean addAll(Collection<? extends T>)
  +void clear()
  +Iterator<T> iterator()
  +boolean remove(Object)
  +boolean removeAll(Collection<? extends Object>)
  +boolean retainAll(Collection<? extends Object>)
  +boolean isEmpty()
  +boolean contains(Object)
  +boolean containsAll(Collection<? extends Object>)
  +int getSize()
  +int getPageNo()
  +void setPageNo(int)
  +int getPageSize()
  +void setPageSize(int)
  +SortedSet<T> page(int, int)
  +int totalPage(int)
  +int current()
  +int totalSize()
  +boolean hasNextPage()
  +boolean hasPreviousPage()
  +int getNextPage()
  +int getPreviousPage()
  +int component2()
  +int component3()
  +PageableSet<T> copy(SortedSet<T>, int, int)
  +int size()
  +T[] toArray(T[])
  +Object[] toArray()
}
class "Cell" as org.toolkit4j.collection.table.Cell<R, C, V> {
  +R getRowKey()
  +C getColumnKey()
  +V getValue()
  +Cell<R, C, V> copy(R, C, V)
}
class "ConcurrentHashTable" as org.toolkit4j.collection.table.ConcurrentHashTable<R, C, V> {
  +boolean contains(R, C)
  +boolean containsRow(R)
  +boolean containsColumn(C)
  +boolean containsValue(V)
  +V get(R, C)
  +boolean isEmpty()
  +int size()
  +void clear()
  +Set<Cell<R, C, V>> cellSet()
  +Set<R> rowKeySet()
  +Set<C> columnKeySet()
  +Collection<V> values()
  +Map<R, Map<C, V>> rowMap()
  +Map<C, Map<R, V>> columnMap()
  +Map<R, V> column(C)
  +Map<C, V> row(R)
  +V remove(R, C)
  +void putAll(Table<? extends R, ? extends C, ? extends V>)
  +V put(R, C, V)
}
class "ConcurrentHashTable$1" as org.toolkit4j.collection.table.ConcurrentHashTable$contains$1 {
  +Boolean invoke(ConcurrentMap<C, V>)
}
class "ConcurrentHashTable$1" as org.toolkit4j.collection.table.ConcurrentHashTable$containsColumn$1 {
  +Boolean invoke(ConcurrentMap<C, V>)
}
class "ConcurrentHashTable$1" as org.toolkit4j.collection.table.ConcurrentHashTable$containsValue$1 {
  +Boolean invoke(ConcurrentMap<C, V>)
}
class "ConcurrentHashTable$1" as org.toolkit4j.collection.table.ConcurrentHashTable$get$1 {
  +V invoke(ConcurrentMap<C, V>)
}
class "ConcurrentHashTable$2" as org.toolkit4j.collection.table.ConcurrentHashTable$internal$2 {
  + {static}2 INSTANCE
  __
  +ConcurrentHashMap<R, ConcurrentHashMap<C, V>> invoke()
}
class "ConcurrentHashTable$1" as org.toolkit4j.collection.table.ConcurrentHashTable$put$1 {
  +ConcurrentHashMap<C, V> invoke(R, ConcurrentHashMap<C, V>)
}
class "ConcurrentHashTable$1" as org.toolkit4j.collection.table.ConcurrentHashTable$putAll$1$1 {
  +ConcurrentHashMap<C, V> invoke(R, ConcurrentHashMap<C, V>)
}
class "ConcurrentHashTable$1" as org.toolkit4j.collection.table.ConcurrentHashTable$size$1 {
  + {static}1 INSTANCE
  __
  +Integer invoke(ConcurrentMap<C, V>)
}
interface "ConcurrentTable" as org.toolkit4j.collection.table.ConcurrentTable<R, C, V> {
  + {abstract}boolean contains(R, C)
  + {abstract}boolean containsRow(R)
  + {abstract}boolean containsColumn(C)
  + {abstract}boolean containsValue(V)
  + {abstract}V get(R, C)
  +Optional<V> getOptional(R, C)
  + {abstract}boolean isEmpty()
  + {abstract}int size()
  + {abstract}void clear()
  + {abstract}V put(R, C, V)
  + {abstract}void putAll(Table<? extends R, ? extends C, ? extends V>)
  + {abstract}V remove(R, C)
  + {abstract}Map<C, V> row(R)
  + {abstract}Map<R, V> column(C)
  + {abstract}Set<Cell<R, C, V>> cellSet()
  + {abstract}Set<R> rowKeySet()
  + {abstract}Set<C> columnKeySet()
  + {abstract}Collection<V> values()
  + {abstract}Map<R, Map<C, V>> rowMap()
  + {abstract}Map<C, Map<R, V>> columnMap()
}
abstract class "AbstractTreeNode" as org.toolkit4j.collection.tree.AbstractTreeNode<T> {
  +T getData()
  +void setData(T)
  +TreeNode<T> getParent()
  +void setParent(TreeNode<T>)
  +void addChild(TreeNode<T>)
  +void addChildren(Collection<? extends TreeNode<T>>)
  +void removeChild(TreeNode<T>)
  +void walk(Consumer<TreeNode<T>>)
  +void parallelWalk(Consumer<TreeNode<T>>)
  +Iterator<TreeNode<T>> iterator()
  +Stream<TreeNode<T>> stream()
  +Stream<TreeNode<T>> parallelStream()
}
class "AbstractTreeNode$1" as org.toolkit4j.collection.tree.AbstractTreeNode$walkRecursive$1 {
  +void invoke(TreeNode<T>)
}
class "ListTreeNode" as org.toolkit4j.collection.tree.ListTreeNode<T> {
  +T getData()
  +void setData(T)
  +TreeNode<T> getParent()
  +void setParent(TreeNode<T>)
  +Collection<TreeNode<T>> getChildren()
  +T component1()
  +TreeNode<T> component2()
  +Collection<TreeNode<T>> component3()
  +ListTreeNode<T> copy(T, TreeNode<T>, Collection<TreeNode<T>>)
}
class "TreeIterator" as org.toolkit4j.collection.tree.TreeIterator<T> {
  +boolean hasNext()
  +TreeNode<T> next()
  +void remove()
}
interface "TreeNode" as org.toolkit4j.collection.tree.TreeNode<T> {
  + {abstract}T getData()
  + {abstract}void setData(T)
  + {abstract}TreeNode<T> getParent()
  + {abstract}void setParent(TreeNode<T>)
  + {abstract}Collection<TreeNode<T>> getChildren()
  +boolean isRoot()
  +boolean isLeaf()
  + {abstract}void addChild(TreeNode<T>)
  + {abstract}void addChildren(Collection<? extends TreeNode<T>>)
  + {abstract}void removeChild(TreeNode<T>)
  + {abstract}Stream<TreeNode<T>> stream()
  + {abstract}Stream<TreeNode<T>> parallelStream()
  + {abstract}void walk(Consumer<TreeNode<T>>)
  + {abstract}void parallelWalk(Consumer<TreeNode<T>>)
  + {abstract}Iterator<TreeNode<T>> iterator()
}
kotlin.jvm.functions.Function0 .u.|> kotlin.Function
kotlin.jvm.functions.Function1 .u.|> kotlin.Function
kotlin.jvm.functions.Function2 .u.|> kotlin.Function
kotlin.jvm.internal.FunctionBase .u.|> kotlin.Function
kotlin.jvm.internal.Lambda .u.|> kotlin.jvm.internal.FunctionBase
kotlin.jvm.internal.Lambda .u.|> kotlin.Function
kotlin.jvm.internal.markers.KMutableCollection .u.|> kotlin.jvm.internal.markers.KMutableIterable
kotlin.jvm.internal.markers.KMutableCollection .u.|> kotlin.jvm.internal.markers.KMappedMarker
kotlin.jvm.internal.markers.KMutableIterable .u.|> kotlin.jvm.internal.markers.KMappedMarker
kotlin.jvm.internal.markers.KMutableIterator .u.|> kotlin.jvm.internal.markers.KMappedMarker
kotlin.jvm.internal.markers.KMutableList .u.|> kotlin.jvm.internal.markers.KMutableCollection
kotlin.jvm.internal.markers.KMutableList .u.|> kotlin.jvm.internal.markers.KMutableIterable
kotlin.jvm.internal.markers.KMutableList .u.|> kotlin.jvm.internal.markers.KMappedMarker
org.toolkit4j.collection.graph.UndirectedGraph .u.|> org.toolkit4j.collection.graph.Graph
org.toolkit4j.collection.graph.UndirectedGraph --> org.toolkit4j.collection.graph.Edge
org.toolkit4j.collection.graph.UndirectedGraph$addVertex$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.graph.UndirectedGraph$addVertex$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.graph.UndirectedGraph$addVertex$1 --> org.toolkit4j.collection.graph.UndirectedGraph$addVertex$1
org.toolkit4j.collection.graph.UndirectedGraph$removeEdge$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.graph.UndirectedGraph$removeEdge$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.graph.UndirectedGraph$removeEdge$2 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.graph.UndirectedGraph$removeEdge$2 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.graph.UndirectedGraph$removeVertex$1$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.graph.UndirectedGraph$removeVertex$1$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.other.HashQueueMap .u.|> kotlin.jvm.internal.markers.KMappedMarker
org.toolkit4j.collection.other.HashQueueMap$add$1$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.other.HashQueueMap$add$1$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.other.HashQueueMap$add$1$1 --> org.toolkit4j.collection.other.HashQueueMap$add$1$1
org.toolkit4j.collection.other.HashQueueMap$offer$1$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.other.HashQueueMap$offer$1$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.other.HashQueueMap$offer$1$1 --> org.toolkit4j.collection.other.HashQueueMap$offer$1$1
org.toolkit4j.collection.pageable.PageableList .u.|> org.toolkit4j.collection.pageable.PageableCollection
org.toolkit4j.collection.pageable.PageableList .u.|> kotlin.jvm.internal.markers.KMutableList
org.toolkit4j.collection.pageable.PageableList .u.|> kotlin.jvm.internal.markers.KMutableCollection
org.toolkit4j.collection.pageable.PageableList .u.|> kotlin.jvm.internal.markers.KMutableIterable
org.toolkit4j.collection.pageable.PageableList .u.|> kotlin.jvm.internal.markers.KMappedMarker
org.toolkit4j.collection.pageable.PageableSet .u.|> org.toolkit4j.collection.pageable.PageableCollection
org.toolkit4j.collection.table.Cell .u.|> com.google.common.collect.Table$Cell
org.toolkit4j.collection.table.ConcurrentHashTable .u.|> org.toolkit4j.collection.table.ConcurrentTable
org.toolkit4j.collection.table.ConcurrentHashTable$contains$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.table.ConcurrentHashTable$contains$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.table.ConcurrentHashTable$containsColumn$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.table.ConcurrentHashTable$containsColumn$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.table.ConcurrentHashTable$containsValue$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.table.ConcurrentHashTable$containsValue$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.table.ConcurrentHashTable$get$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.table.ConcurrentHashTable$get$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.table.ConcurrentHashTable$internal$2 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.table.ConcurrentHashTable$internal$2 .u.|> kotlin.jvm.functions.Function0
org.toolkit4j.collection.table.ConcurrentHashTable$internal$2 --> org.toolkit4j.collection.table.ConcurrentHashTable$internal$2
org.toolkit4j.collection.table.ConcurrentHashTable$put$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.table.ConcurrentHashTable$put$1 .u.|> kotlin.jvm.functions.Function2
org.toolkit4j.collection.table.ConcurrentHashTable$putAll$1$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.table.ConcurrentHashTable$putAll$1$1 .u.|> kotlin.jvm.functions.Function2
org.toolkit4j.collection.table.ConcurrentHashTable$size$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.table.ConcurrentHashTable$size$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.table.ConcurrentHashTable$size$1 --> org.toolkit4j.collection.table.ConcurrentHashTable$size$1
org.toolkit4j.collection.tree.AbstractTreeNode .u.|> org.toolkit4j.collection.tree.TreeNode
org.toolkit4j.collection.tree.AbstractTreeNode --> org.toolkit4j.collection.tree.TreeNode
org.toolkit4j.collection.tree.AbstractTreeNode$walkRecursive$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.collection.tree.AbstractTreeNode$walkRecursive$1 .u.|> kotlin.jvm.functions.Function1
org.toolkit4j.collection.tree.ListTreeNode -u-|> org.toolkit4j.collection.tree.AbstractTreeNode
org.toolkit4j.collection.tree.ListTreeNode --> org.toolkit4j.collection.tree.TreeNode
org.toolkit4j.collection.tree.TreeIterator .u.|> kotlin.jvm.internal.markers.KMutableIterator
org.toolkit4j.collection.tree.TreeIterator .u.|> kotlin.jvm.internal.markers.KMappedMarker
org.toolkit4j.collection.tree.TreeIterator --> org.toolkit4j.collection.tree.TreeNode
@enduml
