@startuml
!pragma useIntermediatePackages false

interface "Function" as kotlin.Function<R> {
}
annotation "Metadata" as kotlin.Metadata {
  + {abstract}int k()
  + {abstract}int[] mv()
  + {abstract}int[] bv()
  + {abstract}String[] d1()
  + {abstract}String[] d2()
  + {abstract}String xs()
  + {abstract}String pn()
  + {abstract}int xi()
}
annotation "SinceKotlin" as kotlin.SinceKotlin {
  + {abstract}String version()
}
enum "AnnotationRetention" as kotlin.annotation.AnnotationRetention {
  SOURCE
  BINARY
  RUNTIME
  __
  + {static}EnumEntries<AnnotationRetention> getEntries()
}
enum "AnnotationTarget" as kotlin.annotation.AnnotationTarget {
  CLASS
  ANNOTATION_CLASS
  TYPE_PARAMETER
  PROPERTY
  FIELD
  LOCAL_VARIABLE
  VALUE_PARAMETER
  CONSTRUCTOR
  FUNCTION
  PROPERTY_GETTER
  PROPERTY_SETTER
  TYPE
  EXPRESSION
  FILE
  TYPEALIAS
  __
  + {static}EnumEntries<AnnotationTarget> getEntries()
}
annotation "MustBeDocumented" as kotlin.annotation.MustBeDocumented {
}
annotation "Retention" as kotlin.annotation.Retention {
  + {abstract}AnnotationRetention value()
}
annotation "Target" as kotlin.annotation.Target {
  + {abstract}AnnotationTarget[] allowedTargets()
}
annotation "JvmName" as kotlin.jvm.JvmName {
  + {abstract}String name()
}
interface "Function0" as kotlin.jvm.functions.Function0<R> {
  + {abstract}R invoke()
}
interface "FunctionBase" as kotlin.jvm.internal.FunctionBase<R> {
  + {abstract}int getArity()
}
abstract class "Lambda" as kotlin.jvm.internal.Lambda<R> {
  +int getArity()
}
annotation "SourceDebugExtension" as kotlin.jvm.internal.SourceDebugExtension {
  + {abstract}String[] value()
}
annotation "NotNull" as org.jetbrains.annotations.NotNull {
  + {abstract}String value()
  + {abstract}Class<? extends Exception> exception()
}
annotation "KtSlf4j" as org.toolkit4j.ktslf4j.KtSlf4j {
  ..
  + {static}Companion Companion
}
class "KtSlf4j$Companion" as org.toolkit4j.ktslf4j.KtSlf4j$Companion {
}
class "Companion$KtSlf4j$1" as org.toolkit4j.ktslf4j.KtSlf4j$Companion$log$1 {
  + {static}1 INSTANCE
  __
  +void invoke()
}
class "PureFuncKt" as org.toolkit4j.ktslf4j.PureFuncKt {
}
interface "Slf4jInterface" as org.toolkit4j.ktslf4j.Slf4jInterface {
  +Logger logger()
}
kotlin.jvm.functions.Function0 .u.|> kotlin.Function
kotlin.jvm.internal.FunctionBase .u.|> kotlin.Function
kotlin.jvm.internal.Lambda .u.|> kotlin.jvm.internal.FunctionBase
kotlin.jvm.internal.Lambda .u.|> kotlin.Function
org.toolkit4j.ktslf4j.KtSlf4j --> org.toolkit4j.ktslf4j.KtSlf4j$Companion
org.toolkit4j.ktslf4j.KtSlf4j$Companion$log$1 -u-|> kotlin.jvm.internal.Lambda
org.toolkit4j.ktslf4j.KtSlf4j$Companion$log$1 .u.|> kotlin.jvm.functions.Function0
org.toolkit4j.ktslf4j.KtSlf4j$Companion$log$1 --> org.toolkit4j.ktslf4j.KtSlf4j$Companion$log$1
@enduml
