import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docs: [
    {
      type: "category",
      label: "Collection",
      link: {
        type: "generated-index",
        title: "Toolkit4j Documentation",
        description: "Learn about the most important Toolkit4j",
        slug: "/category/docusaurus-guides",
        keywords: ["guides"],
        image: "/img/docusaurus.png",
      },
      // items: ["README", "collection"],
      items: [
        "collection/pageable-interface",
        "collection/pageable-list",
        // {
        //   type: "category",
        //   collapsible: false,
        //   label: "Collection",
        //   items: ["collection/pageable-interface", "collection/pageable-list"],
        // },
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
