@startuml
!pragma useIntermediatePackages false

annotation "NonNull" as lombok.NonNull {
}
annotation "NonNls" as org.jetbrains.annotations.NonNls {
}
annotation "NotNull" as org.jetbrains.annotations.NotNull {
  + {abstract}String value()
  + {abstract}Class<? extends Exception> exception()
}
annotation "Nullable" as org.jetbrains.annotations.Nullable {
  + {abstract}String value()
}
interface "Cache" as org.toolkit.spring.boot.cache.api.Cache<K, V> {
  + {abstract}void put(K, V)
  + {abstract}void put(K, V, Duration)
  + {abstract}void put(K, V, long, TimeUnit)
  + {abstract}void putAll(Map<? extends K, ? extends V>)
  + {abstract}int size()
  + {abstract}boolean isEmpty()
  + {abstract}boolean containsKey(K)
  + {abstract}boolean putIfAbsent(K, V)
  + {abstract}void remove(K)
  + {abstract}void removeAll(Collection<K>)
  + {abstract}void clear()
  + {abstract}Collection<K> keys()
  + {abstract}Collection<V> values()
  + {abstract}V compute(K, BiFunction<? super K, ? super V, ? extends V>)
  +Optional<V> computeOptional(K, BiFunction<? super K, ? super V, ? extends V>)
  + {abstract}V computeIfAbsent(K, Function<? super K, ? extends V>)
  +Optional<V> computeIfAbsentOptional(K, Function<? super K, ? extends V>)
  + {abstract}V computeIfPresent(K, Function<? super K, ? extends V>)
  +Optional<V> computeIfPresentOptional(K, Function<? super K, ? extends V>)
  + {abstract}boolean replace(K, V)
  + {abstract}V get(K)
  + {abstract}Map<? extends K, ? extends V> getAll()
  +Optional<V> getOptional(K)
  + {abstract}V getAndRemove(K)
  +Optional<V> getAndRemoveOptional(K)
  +V getOrDefault(K, V)
  + {abstract}String getCacheName()
}
class "CacheConfig" as org.toolkit.spring.boot.cache.api.CacheConfig<K, V> {
  + {static}CacheConfigBuilder builder()
  +Function<K, Object> getKeyConvertor()
  +boolean isEnableNullValue()
  +CacheConfig<K, V> setKeyConvertor(Function<K, Object>)
  +CacheConfig<K, V> setEnableNullValue(boolean)
}
class "CacheConfig$CacheConfigBuilder" as org.toolkit.spring.boot.cache.api.CacheConfig$CacheConfigBuilder<K, V> {
  +CacheConfigBuilder keyConvertor(Function<K, Object>)
  +CacheConfigBuilder enableNullValue(boolean)
  +CacheConfig<K, V> build()
}
interface "CacheFactory" as org.toolkit.spring.boot.cache.api.CacheFactory<K, V> {
  + {abstract}Cache<K, V> create(CacheConfig<K, V>)
}
interface "CacheManager" as org.toolkit.spring.boot.cache.api.CacheManager {
  + {abstract}CacheType getCacheType()
}
enum "CacheType" as org.toolkit.spring.boot.cache.api.CacheType {
  REDIS
  CAFFINE
  HZAELCAST
  IMMUTABLE
}
class "MultiLevelCacheManager" as org.toolkit.spring.boot.cache.api.MultiLevelCacheManager {
  __
  +void createCache(String)
}
org.toolkit.spring.boot.cache.api.MultiLevelCacheManager --> org.toolkit.spring.boot.cache.api.CacheManager
@enduml
